name: "Wait for Netlify Deploy"
description: "Waits for the current GitHub commit Netlify deploy to be ready."
branding:
  icon: "clock"
  color: "blue"
inputs:
  site_id:
    description: "The Netlify site ID to test against, get this from the Netlify UI under site settings."
    required: true
  max_timeout:
    description: "The max time to wait after the deployment is ready for a valid HTTP status code."
    required: false
  context:
    description: "The Netlify deploy context. Can be branch-deploy, production or deploy-preview."
    required: false
outputs:
  deploy_id:
    description: "The Netlify deployment ID"
  url:
    description: "The fully qualified deployment URL"
runs:
  using: "node16"
  main: "index.js"
